### ISSUE TITLE
Inquire QG model checkpoint of NQ Dataset

### ISSUE THREAD

**Issue by hi-i-m-GTooth** [ArvinZhuang/DSI-QG#12]
Hi, Dr. Zhuang. Thanks for your remarkable work. I am truly grateful for the insights your research provides.

While reviewing the resources provided through the repo, I came across the Query Generation Model Checkpoint. This model plays a pivotal role in ensuring the quality of query generation within your work. While I noticed the availability of the Query Generation Model Checkpoint for the XOR Dataset, I couldn't find a similar checkpoint for the Natural Question Dataset.

In light of this, I would like to know if you would consider making available a Query Generation Model Checkpoint for the Natural Question Dataset.

Once again, thank you for your contributions.

**Comment by ArvinZhuang** [comment]
Hi @hi-i-m-GTooth Thanks for your kind words:)
In our paper we did not train a QG model with NQ training data but we directly use [this](https://huggingface.co/castorini/doc2query-t5-large-msmarco) doc2query model checkpoint, which is trained with MSMARCO training data but since NQ and MSMARCO have similar data distribution, this model performs just well.

**Comment by hi-i-m-GTooth** [comment]
Wow, thanks for your instant reply! This helps me.
